export const ocrTestString: string = `SATURDAY NIGHT
SHOWDOWNS
PRO STOCKS, LATE MODELS, SPORTSMAN, SPORT TRUCKS
MAY 1 - CLASSIC CAR SHOW
MAY 2 - OPENING DAY
MAY 8 - SATURDAY NIGHT SHOWDOWN
MAY 15 - SATURDAY NIGHT SHOWDOWN
MAY 22 - SATURDAY NIGHT SHOWDOWN SPECIAI. SHOWS
JUNE 5 - SATURDAY NIGHT SHOWDOWN
JUNE 12 - SATURDAY NIGHT SHOWDOWN WED JUNE 9 - BOSTON LOUIE CLASSIC
JUNE 19 - SATURDAY NIGHT SHOWDOWN ISMA SUPER MODIFIEDS, NEMA, NEMA LITES
JUNE 26 - SATURDAY NIGHT SHOWDOWN
JULY 10 - SATURDAY NIGHT SHOWDOWN WED JUNE 30 - OPEN WHEEL WEDNESDAY
JULY 17 - SATURDAY NIGHT SHOWDOWN TRI TRACK MODS, 350 SUPERS, NEMA LITES
JULY 24 - SATURDAY NIGHT SHOWDOWN WED JULY 28 - BAY STATE SUMMER CLASSIC
ULV R G I LS OO $10,000 P.A.S.S. 150, PASS MODS, SPORTSMAN
AUG 14 - SATURDAY NIGHT SHOWDOWN
AUG 21 - SATURDAY NIGHT SHOWDOWN SUNDAY AUGUST 8 - MONSTER TRUCK MELTDOWN
AUG 28 - SATURDAY NIGHT SHOWDOWN
SEPT 11 - SATURDAY NIGHT SHOWDOWN S o =
SEPT 18 - SATURDAY NIGHT SHOWDOWN Y ST T et
SEPT 25 - FALL CLASSIC
FAST FRIDAYS
LEGENDS, PURE STOCKS,
SPORT FOURS, BANDOLEROS
TP . THRILL SHOWS
JUNE 4 AUG 6
I Rt R MAY 29 - MEMORIAL DAY THRILL SHOW
YT, JULY 3 - INDEPENDENCE DAY THRILL SHOW
JUNE 25 AUG 27 JULY 31 - MID SUMMER THRILL SHOW
JULY 9 SEPT 10 SEPT 4 LABOR DAY FIREWORKS SHOW
JULY16  SEPT17 OCT 9 - PUMPKIN SMASH SPOOKTACTULAR
JULY 23 SEPT 24
SEEKONKSPEEDWAY.COM`;